#!/usr/bin/env python3
"""Validate config/modbus-map.json and generate the PLC address reference."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config" / "modbus-map.json"
OUTPUT = ROOT / "docs" / "plc" / "MODBUS_MAP.md"
SUPPORTED_TYPES = {"BOOL", "UINT", "SCALED_DINT"}


def field_cells(field: dict) -> list[tuple[int, int | None]]:
    if field["type"] == "BOOL":
        bit = field.get("bit")
        if not isinstance(bit, int) or not 0 <= bit < 16:
            raise ValueError(f"{field['name']}: BOOL bit must be 0..15")
        return [(field["offset"], bit)]
    width = 2 if field["type"] == "SCALED_DINT" else 1
    return [(field["offset"] + index, None) for index in range(width)]


def validate(data: dict) -> None:
    words = data["protocol"]["imageWords"]
    if words != 64:
        raise ValueError("protocol imageWords must be 64")

    names: set[str] = set()
    for image_name in ("command", "status"):
        image = data[image_name]
        # Modbus 基址以现场 InoProShop 从站映射为准：该字段为十六进制，
        # 现场填 1000/1100 实际落到 0x1000=4096 / 0x1100=4352。
        expected_base = 4096 if image_name == "command" else 4352
        if image.get("baseAddress") != expected_base:
            raise ValueError(f"{image_name}: baseAddress must be {expected_base}")

        header = image["header"]
        expected_header = (
            {"magic": 0, "version": 1, "sequence": 2, "heartbeat": 3, "tailSequence": 63}
            if image_name == "command"
            else {
                "magic": 0,
                "version": 1,
                "sequence": 2,
                "ack": 3,
                "heartbeat": 4,
                "tailSequence": 63,
            }
        )
        if header != expected_header:
            raise ValueError(f"{image_name}: fixed header layout changed")

        occupied: dict[tuple[int, int | None], str] = {
            (offset, None): f"header.{name}"
            for name, offset in header.items()
        }
        for field in image["fields"]:
            name = field["name"]
            field_type = field["type"]
            if name in names:
                raise ValueError(f"duplicate variable: {name}")
            names.add(name)
            if field_type not in SUPPORTED_TYPES:
                raise ValueError(f"{name}: unsupported type {field_type}")
            if field_type == "SCALED_DINT" and field.get("scale") not in (100, 1000):
                raise ValueError(f"{name}: scale must be 100 or 1000")

            for cell in field_cells(field):
                offset, bit = cell
                if not 0 <= offset < 63:
                    raise ValueError(f"{name}: offset {offset} is outside payload")
                whole_word = (offset, None)
                bit_cells = [key for key in occupied if key[0] == offset]
                if cell in occupied or whole_word in occupied or (bit is None and bit_cells):
                    other = occupied.get(cell) or occupied.get(whole_word) or occupied[bit_cells[0]]
                    raise ValueError(f"{name}: overlaps {other} at offset {offset}")
                occupied[cell] = name


def fixed_rows(image_name: str, image: dict) -> list[tuple[int, str, str, str]]:
    header = image["header"]
    labels = {
        "magic": "protocol magic",
        "version": "major/minor version",
        "sequence": "leading snapshot sequence",
        "ack": "accepted command sequence",
        "heartbeat": "heartbeat counter/echo",
        "tailSequence": "trailing snapshot sequence",
    }
    return [
        (offset, f"_{name}", "WORD", labels[name])
        for name, offset in header.items()
    ]


def field_row(field: dict) -> tuple[int, str, str, str]:
    detail = field.get("zh") or ""
    if field["type"] == "BOOL":
        bit = f"bit {field['bit']}"
        detail = f"{bit}; {detail}" if detail else bit
    elif field["type"] == "SCALED_DINT":
        scale = f"2 WORD, signed, scale ×{field['scale']}, high word first"
        detail = f"{scale}; {detail}" if detail else scale
    return field["offset"], field["name"], field["type"], detail


def render(data: dict, digest: str) -> str:
    protocol = data["protocol"]
    version = f"{protocol['versionMajor']}.{protocol['versionMinor']}"
    lines = [
        "# MODBUS_MAP",
        "",
        "> Generated by `tools/generate_modbus_map.py`; do not edit manually.",
        f"> Source SHA-256: `{digest}`",
        "> 变量中文用法总表见 [HMI.md](HMI.md)。",
        "",
        f"- Protocol: {protocol['name']} v{version}",
        f"- Magic: `0x{protocol['magic']:04X}`",
        f"- Snapshot size: {protocol['imageWords']} WORD",
        f"- Multi-word order: {protocol['wordOrder']}",
        "",
    ]

    for image_name, title in (("command", "Gateway → PLC 命令（Web 写）"), ("status", "PLC → Gateway 状态（Web 读）")):
        image = data[image_name]
        lines.extend(
            [
                f"## {title}",
                "",
                f"Holding registers `{image['baseAddress']}..{image['baseAddress'] + protocol['imageWords'] - 1}`.",
                "",
                "| Offset | Register | Variable | Type | 中文说明 / Detail |",
                "|---:|---:|---|---|---|",
            ]
        )
        rows = fixed_rows(image_name, image) + [field_row(field) for field in image["fields"]]
        rows.sort(key=lambda row: (row[0], row[1]))
        for offset, name, field_type, detail in rows:
            lines.append(
                f"| {offset} | {image['baseAddress'] + offset} | `{name}` | {field_type} | {detail} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    source_bytes = SOURCE.read_bytes()
    data = json.loads(source_bytes)
    validate(data)
    digest = hashlib.sha256(source_bytes).hexdigest()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(data, digest), encoding="utf-8")


if __name__ == "__main__":
    main()
